resources:
- deployment.yaml
- service.yaml
- ingress.yaml

images:
- name: ghcr.io/jhildi/apiservice
  newName: ghcr.io/jhildi/apiservice
  newTag: 6b561e37456c27432d62cf6f6d65c0db543c1547

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- literals:
  - OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY=in_memory
  - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
  - HTTP_PORTS=8080
  - ASPNETCORE_URLS=http://+:8080;
  name: apiservice-env
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
